
/**
 * @file attribs.h
 *
 * Defines the AttribUnion and attrib structures.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: attribs.h.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#ifndef _SAC_ATTRIBS_H_
#define _SAC_ATTRIBS_H_

#include "types.h"


/******************************************************************************
 * For each node a structure of its attributes is defined, named 
 * ATTRIBS_<nodename>
 *****************************************************************************/
struct ATTRIBS_N_ASSIGN
{
};
struct ATTRIBS_N_BINOP
{
  binop Op;
};
struct ATTRIBS_N_BOOL
{
  bool Value;
};
struct ATTRIBS_N_CAST
{
};
struct ATTRIBS_N_CONST
{
};
struct ATTRIBS_N_DO
{
  keyword Value;
};
struct ATTRIBS_N_DOWHILESTAT
{
};
struct ATTRIBS_N_ELSE
{
  keyword Value;
};
struct ATTRIBS_N_ELSEBLOCK
{
};
struct ATTRIBS_N_ENCLOSEDBLOCK
{
};
struct ATTRIBS_N_ENCLOSEDEXPR
{
};
struct ATTRIBS_N_EQUALS
{
  keyword Value;
};
struct ATTRIBS_N_ERROR
{
  char *message;
  compiler_phase_t anyphase;
};
struct ATTRIBS_N_EXPORT
{
  keyword Value;
};
struct ATTRIBS_N_EXPRLIST
{
};
struct ATTRIBS_N_EXTERN
{
  keyword Value;
};
struct ATTRIBS_N_FLOAT
{
  float Value;
};
struct ATTRIBS_N_FOR
{
  keyword Value;
};
struct ATTRIBS_N_FORDEC
{
};
struct ATTRIBS_N_FORSTAT
{
};
struct ATTRIBS_N_FORVARINIT
{
};
struct ATTRIBS_N_FUNBODY
{
};
struct ATTRIBS_N_FUNCALL
{
};
struct ATTRIBS_N_FUNDEC
{
};
struct ATTRIBS_N_FUNDEF
{
};
struct ATTRIBS_N_FUNHEADER
{
};
struct ATTRIBS_N_GLOBALDEC
{
};
struct ATTRIBS_N_GLOBALDEF
{
};
struct ATTRIBS_N_IFKEYWORD
{
  keyword Value;
};
struct ATTRIBS_N_IFSTAT
{
};
struct ATTRIBS_N_KEY_BOOL
{
  keyword Value;
};
struct ATTRIBS_N_KEY_FLOAT
{
  keyword Value;
};
struct ATTRIBS_N_KEY_INT
{
  keyword Value;
};
struct ATTRIBS_N_KEY_VOID
{
  keyword Value;
};
struct ATTRIBS_N_L_BRACKET
{
  keyword Value;
};
struct ATTRIBS_N_L_FL_BRACKET
{
  keyword Value;
};
struct ATTRIBS_N_MONOP
{
  monop Op;
};
struct ATTRIBS_N_NUM
{
  int Value;
};
struct ATTRIBS_N_PARAM
{
};
struct ATTRIBS_N_PARAMLIST
{
};
struct ATTRIBS_N_PROGRAM
{
};
struct ATTRIBS_N_R_BRACKET
{
  keyword Value;
};
struct ATTRIBS_N_R_FL_BRACKET
{
  keyword Value;
};
struct ATTRIBS_N_RETTYPE
{
};
struct ATTRIBS_N_RETURN
{
};
struct ATTRIBS_N_RETURNKEYWORD
{
  keyword Value;
};
struct ATTRIBS_N_STATEMENT
{
};
struct ATTRIBS_N_STATEMENTLIST
{
};
struct ATTRIBS_N_TYPE
{
};
struct ATTRIBS_N_VAR
{
  char *Name;
  node *Decl;
};
struct ATTRIBS_N_VARDEC
{
};
struct ATTRIBS_N_VARDECLIST
{
};
struct ATTRIBS_N_VARLET
{
  char *Name;
  node *Decl;
};
struct ATTRIBS_N_WHILE
{
  keyword Value;
};
struct ATTRIBS_N_WHILESTAT
{
};
/*****************************************************************************
 * This union handles all different types of attributes. Its members are
 * called N_nodename.
 ****************************************************************************/
struct ATTRIBUNION
{
  struct ATTRIBS_N_ASSIGN *N_assign;
  struct ATTRIBS_N_BINOP *N_binop;
  struct ATTRIBS_N_BOOL *N_bool;
  struct ATTRIBS_N_CAST *N_cast;
  struct ATTRIBS_N_CONST *N_const;
  struct ATTRIBS_N_DO *N_do;
  struct ATTRIBS_N_DOWHILESTAT *N_dowhilestat;
  struct ATTRIBS_N_ELSE *N_else;
  struct ATTRIBS_N_ELSEBLOCK *N_elseblock;
  struct ATTRIBS_N_ENCLOSEDBLOCK *N_enclosedblock;
  struct ATTRIBS_N_ENCLOSEDEXPR *N_enclosedexpr;
  struct ATTRIBS_N_EQUALS *N_equals;
  struct ATTRIBS_N_ERROR *N_error;
  struct ATTRIBS_N_EXPORT *N_export;
  struct ATTRIBS_N_EXPRLIST *N_exprlist;
  struct ATTRIBS_N_EXTERN *N_extern;
  struct ATTRIBS_N_FLOAT *N_float;
  struct ATTRIBS_N_FOR *N_for;
  struct ATTRIBS_N_FORDEC *N_fordec;
  struct ATTRIBS_N_FORSTAT *N_forstat;
  struct ATTRIBS_N_FORVARINIT *N_forvarinit;
  struct ATTRIBS_N_FUNBODY *N_funbody;
  struct ATTRIBS_N_FUNCALL *N_funcall;
  struct ATTRIBS_N_FUNDEC *N_fundec;
  struct ATTRIBS_N_FUNDEF *N_fundef;
  struct ATTRIBS_N_FUNHEADER *N_funheader;
  struct ATTRIBS_N_GLOBALDEC *N_globaldec;
  struct ATTRIBS_N_GLOBALDEF *N_globaldef;
  struct ATTRIBS_N_IFKEYWORD *N_ifkeyword;
  struct ATTRIBS_N_IFSTAT *N_ifstat;
  struct ATTRIBS_N_KEY_BOOL *N_key_bool;
  struct ATTRIBS_N_KEY_FLOAT *N_key_float;
  struct ATTRIBS_N_KEY_INT *N_key_int;
  struct ATTRIBS_N_KEY_VOID *N_key_void;
  struct ATTRIBS_N_L_BRACKET *N_l_bracket;
  struct ATTRIBS_N_L_FL_BRACKET *N_l_fl_bracket;
  struct ATTRIBS_N_MONOP *N_monop;
  struct ATTRIBS_N_NUM *N_num;
  struct ATTRIBS_N_PARAM *N_param;
  struct ATTRIBS_N_PARAMLIST *N_paramlist;
  struct ATTRIBS_N_PROGRAM *N_program;
  struct ATTRIBS_N_R_BRACKET *N_r_bracket;
  struct ATTRIBS_N_R_FL_BRACKET *N_r_fl_bracket;
  struct ATTRIBS_N_RETTYPE *N_rettype;
  struct ATTRIBS_N_RETURN *N_return;
  struct ATTRIBS_N_RETURNKEYWORD *N_returnkeyword;
  struct ATTRIBS_N_STATEMENT *N_statement;
  struct ATTRIBS_N_STATEMENTLIST *N_statementlist;
  struct ATTRIBS_N_TYPE *N_type;
  struct ATTRIBS_N_VAR *N_var;
  struct ATTRIBS_N_VARDEC *N_vardec;
  struct ATTRIBS_N_VARDECLIST *N_vardeclist;
  struct ATTRIBS_N_VARLET *N_varlet;
  struct ATTRIBS_N_WHILE *N_while;
  struct ATTRIBS_N_WHILESTAT *N_whilestat;
};
#endif /* _SAC_ATTRIBS_H_ */
