
/**
 * @file check.h
 *
 * Functions to check node structures
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: check.h.xsl 15657 2007-11-13 13:57:30Z cg $.
 * DO NOT EDIT THIS FILE. EDIT THE AST SPEC IN ast.xml INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#ifndef _SAC_CHECK_H_
#define _SAC_CHECK_H_

#include "types.h"

extern node *CHKdoTreeCheck (node * syntax_tree);


extern node *CHKassign (node * arg_node, info * arg_info);
extern node *CHKbinop (node * arg_node, info * arg_info);
extern node *CHKbool (node * arg_node, info * arg_info);
extern node *CHKcast (node * arg_node, info * arg_info);
extern node *CHKconst (node * arg_node, info * arg_info);
extern node *CHKdo (node * arg_node, info * arg_info);
extern node *CHKdowhilestat (node * arg_node, info * arg_info);
extern node *CHKelse (node * arg_node, info * arg_info);
extern node *CHKelseblock (node * arg_node, info * arg_info);
extern node *CHKenclosedblock (node * arg_node, info * arg_info);
extern node *CHKenclosedexpr (node * arg_node, info * arg_info);
extern node *CHKequals (node * arg_node, info * arg_info);
extern node *CHKerror (node * arg_node, info * arg_info);
extern node *CHKexport (node * arg_node, info * arg_info);
extern node *CHKexprlist (node * arg_node, info * arg_info);
extern node *CHKextern (node * arg_node, info * arg_info);
extern node *CHKfloat (node * arg_node, info * arg_info);
extern node *CHKfor (node * arg_node, info * arg_info);
extern node *CHKfordec (node * arg_node, info * arg_info);
extern node *CHKforstat (node * arg_node, info * arg_info);
extern node *CHKforvarinit (node * arg_node, info * arg_info);
extern node *CHKfunbody (node * arg_node, info * arg_info);
extern node *CHKfuncall (node * arg_node, info * arg_info);
extern node *CHKfundec (node * arg_node, info * arg_info);
extern node *CHKfundef (node * arg_node, info * arg_info);
extern node *CHKfunheader (node * arg_node, info * arg_info);
extern node *CHKglobaldec (node * arg_node, info * arg_info);
extern node *CHKglobaldef (node * arg_node, info * arg_info);
extern node *CHKifkeyword (node * arg_node, info * arg_info);
extern node *CHKifstat (node * arg_node, info * arg_info);
extern node *CHKkey_bool (node * arg_node, info * arg_info);
extern node *CHKkey_float (node * arg_node, info * arg_info);
extern node *CHKkey_int (node * arg_node, info * arg_info);
extern node *CHKkey_void (node * arg_node, info * arg_info);
extern node *CHKl_bracket (node * arg_node, info * arg_info);
extern node *CHKl_fl_bracket (node * arg_node, info * arg_info);
extern node *CHKmonop (node * arg_node, info * arg_info);
extern node *CHKnum (node * arg_node, info * arg_info);
extern node *CHKparam (node * arg_node, info * arg_info);
extern node *CHKparamlist (node * arg_node, info * arg_info);
extern node *CHKprogram (node * arg_node, info * arg_info);
extern node *CHKr_bracket (node * arg_node, info * arg_info);
extern node *CHKr_fl_bracket (node * arg_node, info * arg_info);
extern node *CHKrettype (node * arg_node, info * arg_info);
extern node *CHKreturn (node * arg_node, info * arg_info);
extern node *CHKreturnkeyword (node * arg_node, info * arg_info);
extern node *CHKstatement (node * arg_node, info * arg_info);
extern node *CHKstatementlist (node * arg_node, info * arg_info);
extern node *CHKtype (node * arg_node, info * arg_info);
extern node *CHKvar (node * arg_node, info * arg_info);
extern node *CHKvardec (node * arg_node, info * arg_info);
extern node *CHKvardeclist (node * arg_node, info * arg_info);
extern node *CHKvarlet (node * arg_node, info * arg_info);
extern node *CHKwhile (node * arg_node, info * arg_info);
extern node *CHKwhilestat (node * arg_node, info * arg_info);
extern node *CHKenclosedblock (node * arg_node, info * arg_info);
extern node *CHKstatement (node * arg_node, info * arg_info);
extern node *CHKfundec (node * arg_node, info * arg_info);
extern node *CHKfundef (node * arg_node, info * arg_info);
extern node *CHKglobaldec (node * arg_node, info * arg_info);
extern node *CHKglobaldef (node * arg_node, info * arg_info);
extern node *CHKbinop (node * arg_node, info * arg_info);
extern node *CHKmonop (node * arg_node, info * arg_info);
extern node *CHKcast (node * arg_node, info * arg_info);
extern node *CHKvar (node * arg_node, info * arg_info);
extern node *CHKfuncall (node * arg_node, info * arg_info);
extern node *CHKconst (node * arg_node, info * arg_info);
extern node *CHKenclosedexpr (node * arg_node, info * arg_info);
extern node *CHKnum (node * arg_node, info * arg_info);
extern node *CHKfloat (node * arg_node, info * arg_info);
extern node *CHKbool (node * arg_node, info * arg_info);
extern node *CHKkey_void (node * arg_node, info * arg_info);
extern node *CHKkey_int (node * arg_node, info * arg_info);
extern node *CHKkey_float (node * arg_node, info * arg_info);
extern node *CHKkey_bool (node * arg_node, info * arg_info);
extern node *CHKassign (node * arg_node, info * arg_info);
extern node *CHKfuncall (node * arg_node, info * arg_info);
extern node *CHKifstat (node * arg_node, info * arg_info);
extern node *CHKdowhilestat (node * arg_node, info * arg_info);
extern node *CHKwhilestat (node * arg_node, info * arg_info);
extern node *CHKforstat (node * arg_node, info * arg_info);
extern node *CHKkey_int (node * arg_node, info * arg_info);
extern node *CHKkey_float (node * arg_node, info * arg_info);
extern node *CHKkey_bool (node * arg_node, info * arg_info);


#endif /* _SAC_CHECK_H_ */
