
/**
 * @file free_node.h
 *
 * Functions to free node structures
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: copy_node.h.xsl 296 2008-02-26 01:52:31Z sah $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#ifndef _SAC_COPY_NODE_H_
#define _SAC_COPY_NODE_H_

#include "types.h"

extern node *COPYassign (node * arg_node, info * arg_info);
extern node *COPYbinop (node * arg_node, info * arg_info);
extern node *COPYbool (node * arg_node, info * arg_info);
extern node *COPYcast (node * arg_node, info * arg_info);
extern node *COPYconst (node * arg_node, info * arg_info);
extern node *COPYdo (node * arg_node, info * arg_info);
extern node *COPYdowhilestat (node * arg_node, info * arg_info);
extern node *COPYelse (node * arg_node, info * arg_info);
extern node *COPYelseblock (node * arg_node, info * arg_info);
extern node *COPYenclosedblock (node * arg_node, info * arg_info);
extern node *COPYenclosedexpr (node * arg_node, info * arg_info);
extern node *COPYequals (node * arg_node, info * arg_info);
extern node *COPYerror (node * arg_node, info * arg_info);
extern node *COPYexport (node * arg_node, info * arg_info);
extern node *COPYexprlist (node * arg_node, info * arg_info);
extern node *COPYextern (node * arg_node, info * arg_info);
extern node *COPYfloat (node * arg_node, info * arg_info);
extern node *COPYfor (node * arg_node, info * arg_info);
extern node *COPYfordec (node * arg_node, info * arg_info);
extern node *COPYforstat (node * arg_node, info * arg_info);
extern node *COPYforvarinit (node * arg_node, info * arg_info);
extern node *COPYfunbody (node * arg_node, info * arg_info);
extern node *COPYfuncall (node * arg_node, info * arg_info);
extern node *COPYfundec (node * arg_node, info * arg_info);
extern node *COPYfundef (node * arg_node, info * arg_info);
extern node *COPYfunheader (node * arg_node, info * arg_info);
extern node *COPYglobaldec (node * arg_node, info * arg_info);
extern node *COPYglobaldef (node * arg_node, info * arg_info);
extern node *COPYifkeyword (node * arg_node, info * arg_info);
extern node *COPYifstat (node * arg_node, info * arg_info);
extern node *COPYkey_bool (node * arg_node, info * arg_info);
extern node *COPYkey_float (node * arg_node, info * arg_info);
extern node *COPYkey_int (node * arg_node, info * arg_info);
extern node *COPYkey_void (node * arg_node, info * arg_info);
extern node *COPYl_bracket (node * arg_node, info * arg_info);
extern node *COPYl_fl_bracket (node * arg_node, info * arg_info);
extern node *COPYmonop (node * arg_node, info * arg_info);
extern node *COPYnum (node * arg_node, info * arg_info);
extern node *COPYparam (node * arg_node, info * arg_info);
extern node *COPYparamlist (node * arg_node, info * arg_info);
extern node *COPYprogram (node * arg_node, info * arg_info);
extern node *COPYr_bracket (node * arg_node, info * arg_info);
extern node *COPYr_fl_bracket (node * arg_node, info * arg_info);
extern node *COPYrettype (node * arg_node, info * arg_info);
extern node *COPYreturn (node * arg_node, info * arg_info);
extern node *COPYreturnkeyword (node * arg_node, info * arg_info);
extern node *COPYstatement (node * arg_node, info * arg_info);
extern node *COPYstatementlist (node * arg_node, info * arg_info);
extern node *COPYtype (node * arg_node, info * arg_info);
extern node *COPYvar (node * arg_node, info * arg_info);
extern node *COPYvardec (node * arg_node, info * arg_info);
extern node *COPYvardeclist (node * arg_node, info * arg_info);
extern node *COPYvarlet (node * arg_node, info * arg_info);
extern node *COPYwhile (node * arg_node, info * arg_info);
extern node *COPYwhilestat (node * arg_node, info * arg_info);

#endif /* _SAC_COPY_NODE_H_ */
