
/**
 * @file copy_node.c
 *
 * Functions needed by copy traversal.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * copy_node.c.xsl.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

/**
 * @defgroup copy Copy Tree Functions.
 *
 * Functions needed by copy traversal.
 *
 * @{
 */


#include "copy_node.h"
#include "copy_info.h"
#include "traverse.h"
#include "dbug.h"
#include "tree_basic.h"
#include "str.h"
#include "lookup_table.h"


#define COPYTRAV( node, info) (node != NULL) ? TRAVdo( node, info) : node


/** <!--******************************************************************-->
 *
 * @fn COPYassign
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Assign node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYassign (node * arg_node, info * arg_info)
{
  node *result = TBmakeAssign (NULL, NULL);
  DBUG_ENTER ("COPYassign");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  ASSIGN_LET (result) = COPYTRAV (ASSIGN_LET (arg_node), arg_info);
  ASSIGN_EXPR (result) = COPYTRAV (ASSIGN_EXPR (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYbinop
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node BinOp node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYbinop (node * arg_node, info * arg_info)
{
  node *result = TBmakeBinop (BO_unknown, NULL, NULL);
  DBUG_ENTER ("COPYbinop");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  BINOP_OP (result) = BINOP_OP (arg_node);
  /* Copy sons */
  BINOP_LEFT (result) = COPYTRAV (BINOP_LEFT (arg_node), arg_info);
  BINOP_RIGHT (result) = COPYTRAV (BINOP_RIGHT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYbool
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Bool node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYbool (node * arg_node, info * arg_info)
{
  node *result = TBmakeBool (FALSE);
  DBUG_ENTER ("COPYbool");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  BOOL_VALUE (result) = BOOL_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYcast
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Cast node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYcast (node * arg_node, info * arg_info)
{
  node *result = TBmakeCast (NULL, NULL, NULL, NULL);
  DBUG_ENTER ("COPYcast");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  CAST_L_BRACKET (result) = COPYTRAV (CAST_L_BRACKET (arg_node), arg_info);
  CAST_TYPE (result) = COPYTRAV (CAST_TYPE (arg_node), arg_info);
  CAST_R_BRACKET (result) = COPYTRAV (CAST_R_BRACKET (arg_node), arg_info);
  CAST_EXPR (result) = COPYTRAV (CAST_EXPR (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYconst
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Const node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYconst (node * arg_node, info * arg_info)
{
  node *result = TBmakeConst (NULL);
  DBUG_ENTER ("COPYconst");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  CONST_SET_CONST (result) = COPYTRAV (CONST_SET_CONST (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYdo
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Do node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYdo (node * arg_node, info * arg_info)
{
  node *result = TBmakeDo (Key_do);
  DBUG_ENTER ("COPYdo");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  DO_VALUE (result) = DO_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYdowhilestat
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node DoWhileStat node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYdowhilestat (node * arg_node, info * arg_info)
{
  node *result = TBmakeDowhilestat (NULL, NULL, NULL, NULL);
  DBUG_ENTER ("COPYdowhilestat");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  DOWHILESTAT_DO (result) = COPYTRAV (DOWHILESTAT_DO (arg_node), arg_info);
  DOWHILESTAT_BLOCK (result) =
    COPYTRAV (DOWHILESTAT_BLOCK (arg_node), arg_info);
  DOWHILESTAT_WHILE (result) =
    COPYTRAV (DOWHILESTAT_WHILE (arg_node), arg_info);
  DOWHILESTAT_EXPR (result) =
    COPYTRAV (DOWHILESTAT_EXPR (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYelse
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Else node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYelse (node * arg_node, info * arg_info)
{
  node *result = TBmakeElse (Key_else);
  DBUG_ENTER ("COPYelse");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  ELSE_VALUE (result) = ELSE_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYelseblock
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node ElseBlock node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYelseblock (node * arg_node, info * arg_info)
{
  node *result = TBmakeElseblock (NULL, NULL);
  DBUG_ENTER ("COPYelseblock");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  ELSEBLOCK_ELSE (result) = COPYTRAV (ELSEBLOCK_ELSE (arg_node), arg_info);
  ELSEBLOCK_BLOCK (result) = COPYTRAV (ELSEBLOCK_BLOCK (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYenclosedblock
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node EnclosedBlock node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYenclosedblock (node * arg_node, info * arg_info)
{
  node *result = TBmakeEnclosedblock (NULL, NULL, NULL);
  DBUG_ENTER ("COPYenclosedblock");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  ENCLOSEDBLOCK_L_FL_BRACKET (result) =
    COPYTRAV (ENCLOSEDBLOCK_L_FL_BRACKET (arg_node), arg_info);
  ENCLOSEDBLOCK_STATEMENTLIST (result) =
    COPYTRAV (ENCLOSEDBLOCK_STATEMENTLIST (arg_node), arg_info);
  ENCLOSEDBLOCK_R_FL_BRACKET (result) =
    COPYTRAV (ENCLOSEDBLOCK_R_FL_BRACKET (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYenclosedexpr
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node EnclosedExpr node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYenclosedexpr (node * arg_node, info * arg_info)
{
  node *result = TBmakeEnclosedexpr (NULL, NULL, NULL);
  DBUG_ENTER ("COPYenclosedexpr");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  ENCLOSEDEXPR_L_BRACKET (result) =
    COPYTRAV (ENCLOSEDEXPR_L_BRACKET (arg_node), arg_info);
  ENCLOSEDEXPR_EXPR (result) =
    COPYTRAV (ENCLOSEDEXPR_EXPR (arg_node), arg_info);
  ENCLOSEDEXPR_R_BRACKET (result) =
    COPYTRAV (ENCLOSEDEXPR_R_BRACKET (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYequals
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Equals node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYequals (node * arg_node, info * arg_info)
{
  node *result = TBmakeEquals (Key_equals);
  DBUG_ENTER ("COPYequals");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  EQUALS_VALUE (result) = EQUALS_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYerror
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Error node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYerror (node * arg_node, info * arg_info)
{
  node *result = TBmakeError (NULL, PH_initial, NULL);
  DBUG_ENTER ("COPYerror");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  ERROR_MESSAGE (result) = STRcpy (ERROR_MESSAGE (arg_node));
  ERROR_ANYPHASE (result) = ERROR_ANYPHASE (arg_node);
  /* Copy sons */
  ERROR_NEXT (result) = COPYTRAV (ERROR_NEXT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYexport
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Export node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYexport (node * arg_node, info * arg_info)
{
  node *result = TBmakeExport (Key_export);
  DBUG_ENTER ("COPYexport");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  EXPORT_VALUE (result) = EXPORT_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYexprlist
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node ExprList node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYexprlist (node * arg_node, info * arg_info)
{
  node *result = TBmakeExprlist (NULL, NULL);
  DBUG_ENTER ("COPYexprlist");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  EXPRLIST_EXPR (result) = COPYTRAV (EXPRLIST_EXPR (arg_node), arg_info);
  EXPRLIST_NEXT (result) = COPYTRAV (EXPRLIST_NEXT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYextern
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Extern node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYextern (node * arg_node, info * arg_info)
{
  node *result = TBmakeExtern (Key_extern);
  DBUG_ENTER ("COPYextern");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  EXTERN_VALUE (result) = EXTERN_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfloat
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Float node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfloat (node * arg_node, info * arg_info)
{
  node *result = TBmakeFloat (0.0);
  DBUG_ENTER ("COPYfloat");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  FLOAT_VALUE (result) = FLOAT_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfor
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node For node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfor (node * arg_node, info * arg_info)
{
  node *result = TBmakeFor (Key_for);
  DBUG_ENTER ("COPYfor");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  FOR_VALUE (result) = FOR_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfordec
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node ForDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfordec (node * arg_node, info * arg_info)
{
  node *result = TBmakeFordec (NULL, NULL, NULL);
  DBUG_ENTER ("COPYfordec");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  FORDEC_TYPE (result) = COPYTRAV (FORDEC_TYPE (arg_node), arg_info);
  FORDEC_FORVARINIT (result) =
    COPYTRAV (FORDEC_FORVARINIT (arg_node), arg_info);
  FORDEC_EXPR (result) = COPYTRAV (FORDEC_EXPR (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYforstat
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node ForStat node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYforstat (node * arg_node, info * arg_info)
{
  node *result = TBmakeForstat (NULL, NULL, NULL);
  DBUG_ENTER ("COPYforstat");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  FORSTAT_FOR (result) = COPYTRAV (FORSTAT_FOR (arg_node), arg_info);
  FORSTAT_FORDEC (result) = COPYTRAV (FORSTAT_FORDEC (arg_node), arg_info);
  FORSTAT_BLOCK (result) = COPYTRAV (FORSTAT_BLOCK (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYforvarinit
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node ForVarInit node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYforvarinit (node * arg_node, info * arg_info)
{
  node *result = TBmakeForvarinit (NULL, NULL, NULL);
  DBUG_ENTER ("COPYforvarinit");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  FORVARINIT_VARLET (result) =
    COPYTRAV (FORVARINIT_VARLET (arg_node), arg_info);
  FORVARINIT_EQUALS (result) =
    COPYTRAV (FORVARINIT_EQUALS (arg_node), arg_info);
  FORVARINIT_EXPR (result) = COPYTRAV (FORVARINIT_EXPR (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfunbody
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunBody node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfunbody (node * arg_node, info * arg_info)
{
  node *result = TBmakeFunbody ();
  DBUG_ENTER ("COPYfunbody");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfuncall
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunCall node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfuncall (node * arg_node, info * arg_info)
{
  node *result = TBmakeFuncall (NULL, NULL);
  DBUG_ENTER ("COPYfuncall");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  FUNCALL_VAR (result) = COPYTRAV (FUNCALL_VAR (arg_node), arg_info);
  FUNCALL_EXPRLIST (result) =
    COPYTRAV (FUNCALL_EXPRLIST (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfundec
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfundec (node * arg_node, info * arg_info)
{
  node *result = TBmakeFundec (NULL, NULL);
  DBUG_ENTER ("COPYfundec");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  FUNDEC_EXTERN (result) = COPYTRAV (FUNDEC_EXTERN (arg_node), arg_info);
  FUNDEC_FUNHEADER (result) =
    COPYTRAV (FUNDEC_FUNHEADER (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfundef
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunDef node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfundef (node * arg_node, info * arg_info)
{
  node *result = TBmakeFundef (NULL, NULL, NULL);
  DBUG_ENTER ("COPYfundef");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  FUNDEF_EXPORT (result) = COPYTRAV (FUNDEF_EXPORT (arg_node), arg_info);
  FUNDEF_FUNHEADER (result) =
    COPYTRAV (FUNDEF_FUNHEADER (arg_node), arg_info);
  FUNDEF_FUNBODY (result) = COPYTRAV (FUNDEF_FUNBODY (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfunheader
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunHeader node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfunheader (node * arg_node, info * arg_info)
{
  node *result = TBmakeFunheader (NULL, NULL, NULL);
  DBUG_ENTER ("COPYfunheader");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  FUNHEADER_RETTYPE (result) =
    COPYTRAV (FUNHEADER_RETTYPE (arg_node), arg_info);
  FUNHEADER_VAR (result) = COPYTRAV (FUNHEADER_VAR (arg_node), arg_info);
  FUNHEADER_PARAMLIST (result) =
    COPYTRAV (FUNHEADER_PARAMLIST (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYglobaldec
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node GlobalDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYglobaldec (node * arg_node, info * arg_info)
{
  node *result = TBmakeGlobaldec (NULL, NULL, NULL);
  DBUG_ENTER ("COPYglobaldec");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  GLOBALDEC_EXTERN (result) =
    COPYTRAV (GLOBALDEC_EXTERN (arg_node), arg_info);
  GLOBALDEC_TYPE (result) = COPYTRAV (GLOBALDEC_TYPE (arg_node), arg_info);
  GLOBALDEC_VAR (result) = COPYTRAV (GLOBALDEC_VAR (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYglobaldef
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node GlobalDef node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYglobaldef (node * arg_node, info * arg_info)
{
  node *result = TBmakeGlobaldef (NULL, NULL, NULL, NULL);
  DBUG_ENTER ("COPYglobaldef");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  GLOBALDEF_EXPORT (result) =
    COPYTRAV (GLOBALDEF_EXPORT (arg_node), arg_info);
  GLOBALDEF_TYPE (result) = COPYTRAV (GLOBALDEF_TYPE (arg_node), arg_info);
  GLOBALDEF_VAR (result) = COPYTRAV (GLOBALDEF_VAR (arg_node), arg_info);
  GLOBALDEF_EXPR (result) = COPYTRAV (GLOBALDEF_EXPR (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYifkeyword
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node IfKeyword node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYifkeyword (node * arg_node, info * arg_info)
{
  node *result = TBmakeIfkeyword (Key_if);
  DBUG_ENTER ("COPYifkeyword");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  IFKEYWORD_VALUE (result) = IFKEYWORD_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYifstat
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node IfStat node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYifstat (node * arg_node, info * arg_info)
{
  node *result = TBmakeIfstat (NULL, NULL, NULL, NULL, NULL, NULL);
  DBUG_ENTER ("COPYifstat");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  IFSTAT_IF (result) = COPYTRAV (IFSTAT_IF (arg_node), arg_info);
  IFSTAT_L_BRACKET (result) =
    COPYTRAV (IFSTAT_L_BRACKET (arg_node), arg_info);
  IFSTAT_EXPR (result) = COPYTRAV (IFSTAT_EXPR (arg_node), arg_info);
  IFSTAT_R_BRACKET (result) =
    COPYTRAV (IFSTAT_R_BRACKET (arg_node), arg_info);
  IFSTAT_BLOCK (result) = COPYTRAV (IFSTAT_BLOCK (arg_node), arg_info);
  IFSTAT_ELSEBLOCK (result) =
    COPYTRAV (IFSTAT_ELSEBLOCK (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYkey_bool
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Key_Bool node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYkey_bool (node * arg_node, info * arg_info)
{
  node *result = TBmakeKey_bool (Key_bool);
  DBUG_ENTER ("COPYkey_bool");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  KEY_BOOL_VALUE (result) = KEY_BOOL_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYkey_float
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Key_Float node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYkey_float (node * arg_node, info * arg_info)
{
  node *result = TBmakeKey_float (Key_float);
  DBUG_ENTER ("COPYkey_float");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  KEY_FLOAT_VALUE (result) = KEY_FLOAT_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYkey_int
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Key_Int node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYkey_int (node * arg_node, info * arg_info)
{
  node *result = TBmakeKey_int (Key_int);
  DBUG_ENTER ("COPYkey_int");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  KEY_INT_VALUE (result) = KEY_INT_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYkey_void
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Key_Void node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYkey_void (node * arg_node, info * arg_info)
{
  node *result = TBmakeKey_void (Key_void);
  DBUG_ENTER ("COPYkey_void");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  KEY_VOID_VALUE (result) = KEY_VOID_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYl_bracket
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node L_Bracket node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYl_bracket (node * arg_node, info * arg_info)
{
  node *result = TBmakeL_bracket (Key_L_Bracket);
  DBUG_ENTER ("COPYl_bracket");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  L_BRACKET_VALUE (result) = L_BRACKET_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYl_fl_bracket
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node L_FL_Bracket node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYl_fl_bracket (node * arg_node, info * arg_info)
{
  node *result = TBmakeL_fl_bracket (Key_L_FL_Bracket);
  DBUG_ENTER ("COPYl_fl_bracket");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  L_FL_BRACKET_VALUE (result) = L_FL_BRACKET_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYmonop
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node MonOp node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYmonop (node * arg_node, info * arg_info)
{
  node *result = TBmakeMonop (MO_unknown, NULL);
  DBUG_ENTER ("COPYmonop");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  MONOP_OP (result) = MONOP_OP (arg_node);
  /* Copy sons */
  MONOP_RIGHT (result) = COPYTRAV (MONOP_RIGHT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYnum
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Num node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYnum (node * arg_node, info * arg_info)
{
  node *result = TBmakeNum (0);
  DBUG_ENTER ("COPYnum");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  NUM_VALUE (result) = NUM_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYparam
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Param node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYparam (node * arg_node, info * arg_info)
{
  node *result = TBmakeParam (NULL, NULL);
  DBUG_ENTER ("COPYparam");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  PARAM_TYPE (result) = COPYTRAV (PARAM_TYPE (arg_node), arg_info);
  PARAM_VAR (result) = COPYTRAV (PARAM_VAR (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYparamlist
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node ParamList node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYparamlist (node * arg_node, info * arg_info)
{
  node *result = TBmakeParamlist (NULL, NULL);
  DBUG_ENTER ("COPYparamlist");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  PARAMLIST_PARAM (result) = COPYTRAV (PARAMLIST_PARAM (arg_node), arg_info);
  PARAMLIST_NEXT (result) = COPYTRAV (PARAMLIST_NEXT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYprogram
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Program node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYprogram (node * arg_node, info * arg_info)
{
  node *result = TBmakeProgram (NULL, NULL);
  DBUG_ENTER ("COPYprogram");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  PROGRAM_CODEBLOCK (result) =
    COPYTRAV (PROGRAM_CODEBLOCK (arg_node), arg_info);
  PROGRAM_NEXT (result) = COPYTRAV (PROGRAM_NEXT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYr_bracket
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node R_Bracket node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYr_bracket (node * arg_node, info * arg_info)
{
  node *result = TBmakeR_bracket (Key_R_Bracket);
  DBUG_ENTER ("COPYr_bracket");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  R_BRACKET_VALUE (result) = R_BRACKET_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYr_fl_bracket
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node R_FL_Bracket node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYr_fl_bracket (node * arg_node, info * arg_info)
{
  node *result = TBmakeR_fl_bracket (Key_R_FL_Bracket);
  DBUG_ENTER ("COPYr_fl_bracket");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  R_FL_BRACKET_VALUE (result) = R_FL_BRACKET_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYrettype
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node RetType node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYrettype (node * arg_node, info * arg_info)
{
  node *result = TBmakeRettype (NULL);
  DBUG_ENTER ("COPYrettype");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  RETTYPE_SET_RETTYPE (result) =
    COPYTRAV (RETTYPE_SET_RETTYPE (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYreturn
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Return node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYreturn (node * arg_node, info * arg_info)
{
  node *result = TBmakeReturn (NULL, NULL);
  DBUG_ENTER ("COPYreturn");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  RETURN_RETURNKEYWORD (result) =
    COPYTRAV (RETURN_RETURNKEYWORD (arg_node), arg_info);
  RETURN_EXPR (result) = COPYTRAV (RETURN_EXPR (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYreturnkeyword
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node ReturnKeyword node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYreturnkeyword (node * arg_node, info * arg_info)
{
  node *result = TBmakeReturnkeyword (Key_return);
  DBUG_ENTER ("COPYreturnkeyword");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  RETURNKEYWORD_VALUE (result) = RETURNKEYWORD_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYstatement
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Statement node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYstatement (node * arg_node, info * arg_info)
{
  node *result = TBmakeStatement (NULL);
  DBUG_ENTER ("COPYstatement");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  STATEMENT_SET_STATEMENT (result) =
    COPYTRAV (STATEMENT_SET_STATEMENT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYstatementlist
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node StatementList node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYstatementlist (node * arg_node, info * arg_info)
{
  node *result = TBmakeStatementlist (NULL, NULL);
  DBUG_ENTER ("COPYstatementlist");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  STATEMENTLIST_STATEMENT (result) =
    COPYTRAV (STATEMENTLIST_STATEMENT (arg_node), arg_info);
  STATEMENTLIST_NEXT (result) =
    COPYTRAV (STATEMENTLIST_NEXT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYtype
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Type node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYtype (node * arg_node, info * arg_info)
{
  node *result = TBmakeType (NULL);
  DBUG_ENTER ("COPYtype");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  TYPE_SET_TYPE (result) = COPYTRAV (TYPE_SET_TYPE (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYvar
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Var node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYvar (node * arg_node, info * arg_info)
{
  node *result = TBmakeVar (NULL);
  DBUG_ENTER ("COPYvar");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  VAR_NAME (result) = STRcpy (VAR_NAME (arg_node));
  VAR_DECL (result) =
    LUTsearchInLutPp (INFO_LUT (arg_info), VAR_DECL (arg_node));
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYvardec
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node VarDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYvardec (node * arg_node, info * arg_info)
{
  node *result = TBmakeVardec (NULL, NULL, NULL);
  DBUG_ENTER ("COPYvardec");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  VARDEC_TYPE (result) = COPYTRAV (VARDEC_TYPE (arg_node), arg_info);
  VARDEC_VAR (result) = COPYTRAV (VARDEC_VAR (arg_node), arg_info);
  VARDEC_EXPR (result) = COPYTRAV (VARDEC_EXPR (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYvardeclist
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node VarDecList node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYvardeclist (node * arg_node, info * arg_info)
{
  node *result = TBmakeVardeclist (NULL, NULL);
  DBUG_ENTER ("COPYvardeclist");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  VARDECLIST_VARDEC (result) =
    COPYTRAV (VARDECLIST_VARDEC (arg_node), arg_info);
  VARDECLIST_NEXT (result) = COPYTRAV (VARDECLIST_NEXT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYvarlet
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node VarLet node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYvarlet (node * arg_node, info * arg_info)
{
  node *result = TBmakeVarlet (NULL);
  DBUG_ENTER ("COPYvarlet");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  VARLET_NAME (result) = STRcpy (VARLET_NAME (arg_node));
  VARLET_DECL (result) =
    LUTsearchInLutPp (INFO_LUT (arg_info), VARLET_DECL (arg_node));
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYwhile
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node While node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYwhile (node * arg_node, info * arg_info)
{
  node *result = TBmakeWhile (Key_while);
  DBUG_ENTER ("COPYwhile");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  WHILE_VALUE (result) = WHILE_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYwhilestat
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node WhileStat node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYwhilestat (node * arg_node, info * arg_info)
{
  node *result = TBmakeWhilestat (NULL, NULL, NULL);
  DBUG_ENTER ("COPYwhilestat");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  WHILESTAT_WHILE (result) = COPYTRAV (WHILESTAT_WHILE (arg_node), arg_info);
  WHILESTAT_EXPR (result) = COPYTRAV (WHILESTAT_EXPR (arg_node), arg_info);
  WHILESTAT_BLOCK (result) = COPYTRAV (WHILESTAT_BLOCK (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/**
 * @}
 */
