
/**
 * @file free_node.c
 *
 * Functions needed by free traversal.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: free_node.c.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

/**
 * @defgroup free Free Tree Functions.
 *
 * Functions needed by free traversal.
 *
 * @{
 */


#include "free.h"
#include "free_node.h"
#include "free_attribs.h"
#include "free_info.h"
#include "tree_basic.h"
#include "traverse.h"
#include "str.h"
#include "memory.h"
#include "dbug.h"

#define FREETRAV( node, info) (node != NULL) ? TRAVdo( node, info) : node
#define FREECOND( node, info)                                    \
  (INFO_FREE_FLAG( info) != arg_node)                            \
    ? FREETRAV( node, info)                                      \
    : (node)


/** <!--******************************************************************-->
 *
 * @fn FREEassign
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Assign node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEassign (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEassign");
  DBUG_PRINT ("FREE", ("Processing node N_assign at " F_PTR, arg_node));
  ASSIGN_LET (arg_node) = FREETRAV (ASSIGN_LET (arg_node), arg_info);
  ASSIGN_EXPR (arg_node) = FREETRAV (ASSIGN_EXPR (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_assign = MEMfree (arg_node->sons.N_assign);
  arg_node->attribs.N_assign = MEMfree (arg_node->attribs.N_assign);
  DBUG_PRINT ("FREE", ("Processing node N_assign at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEbinop
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node BinOp node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEbinop (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEbinop");
  DBUG_PRINT ("FREE", ("Processing node N_binop at " F_PTR, arg_node));
  BINOP_LEFT (arg_node) = FREETRAV (BINOP_LEFT (arg_node), arg_info);
  BINOP_RIGHT (arg_node) = FREETRAV (BINOP_RIGHT (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_binop = MEMfree (arg_node->sons.N_binop);
  arg_node->attribs.N_binop = MEMfree (arg_node->attribs.N_binop);
  DBUG_PRINT ("FREE", ("Processing node N_binop at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEbool
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Bool node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEbool (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEbool");
  DBUG_PRINT ("FREE", ("Processing node N_bool at " F_PTR, arg_node));
  result = NULL;
  arg_node->sons.N_bool = MEMfree (arg_node->sons.N_bool);
  arg_node->attribs.N_bool = MEMfree (arg_node->attribs.N_bool);
  DBUG_PRINT ("FREE", ("Processing node N_bool at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEcast
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Cast node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEcast (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEcast");
  DBUG_PRINT ("FREE", ("Processing node N_cast at " F_PTR, arg_node));
  CAST_L_BRACKET (arg_node) = FREETRAV (CAST_L_BRACKET (arg_node), arg_info);
  CAST_TYPE (arg_node) = FREETRAV (CAST_TYPE (arg_node), arg_info);
  CAST_R_BRACKET (arg_node) = FREETRAV (CAST_R_BRACKET (arg_node), arg_info);
  CAST_EXPR (arg_node) = FREETRAV (CAST_EXPR (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_cast = MEMfree (arg_node->sons.N_cast);
  arg_node->attribs.N_cast = MEMfree (arg_node->attribs.N_cast);
  DBUG_PRINT ("FREE", ("Processing node N_cast at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEconst
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Const node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEconst (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEconst");
  DBUG_PRINT ("FREE", ("Processing node N_const at " F_PTR, arg_node));
  CONST_SET_CONST (arg_node) =
    FREETRAV (CONST_SET_CONST (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_const = MEMfree (arg_node->sons.N_const);
  arg_node->attribs.N_const = MEMfree (arg_node->attribs.N_const);
  DBUG_PRINT ("FREE", ("Processing node N_const at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEdo
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Do node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEdo (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEdo");
  DBUG_PRINT ("FREE", ("Processing node N_do at " F_PTR, arg_node));
  result = NULL;
  arg_node->sons.N_do = MEMfree (arg_node->sons.N_do);
  arg_node->attribs.N_do = MEMfree (arg_node->attribs.N_do);
  DBUG_PRINT ("FREE", ("Processing node N_do at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEdowhilestat
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node DoWhileStat node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEdowhilestat (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEdowhilestat");
  DBUG_PRINT ("FREE", ("Processing node N_dowhilestat at " F_PTR, arg_node));
  DOWHILESTAT_DO (arg_node) = FREETRAV (DOWHILESTAT_DO (arg_node), arg_info);
  DOWHILESTAT_BLOCK (arg_node) =
    FREETRAV (DOWHILESTAT_BLOCK (arg_node), arg_info);
  DOWHILESTAT_WHILE (arg_node) =
    FREETRAV (DOWHILESTAT_WHILE (arg_node), arg_info);
  DOWHILESTAT_EXPR (arg_node) =
    FREETRAV (DOWHILESTAT_EXPR (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_dowhilestat = MEMfree (arg_node->sons.N_dowhilestat);
  arg_node->attribs.N_dowhilestat = MEMfree (arg_node->attribs.N_dowhilestat);
  DBUG_PRINT ("FREE", ("Processing node N_dowhilestat at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEelse
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Else node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEelse (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEelse");
  DBUG_PRINT ("FREE", ("Processing node N_else at " F_PTR, arg_node));
  result = NULL;
  arg_node->sons.N_else = MEMfree (arg_node->sons.N_else);
  arg_node->attribs.N_else = MEMfree (arg_node->attribs.N_else);
  DBUG_PRINT ("FREE", ("Processing node N_else at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEelseblock
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node ElseBlock node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEelseblock (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEelseblock");
  DBUG_PRINT ("FREE", ("Processing node N_elseblock at " F_PTR, arg_node));
  ELSEBLOCK_ELSE (arg_node) = FREETRAV (ELSEBLOCK_ELSE (arg_node), arg_info);
  ELSEBLOCK_BLOCK (arg_node) =
    FREETRAV (ELSEBLOCK_BLOCK (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_elseblock = MEMfree (arg_node->sons.N_elseblock);
  arg_node->attribs.N_elseblock = MEMfree (arg_node->attribs.N_elseblock);
  DBUG_PRINT ("FREE", ("Processing node N_elseblock at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEenclosedblock
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node EnclosedBlock node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEenclosedblock (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEenclosedblock");
  DBUG_PRINT ("FREE",
	      ("Processing node N_enclosedblock at " F_PTR, arg_node));
  ENCLOSEDBLOCK_L_FL_BRACKET (arg_node) =
    FREETRAV (ENCLOSEDBLOCK_L_FL_BRACKET (arg_node), arg_info);
  ENCLOSEDBLOCK_STATEMENTLIST (arg_node) =
    FREETRAV (ENCLOSEDBLOCK_STATEMENTLIST (arg_node), arg_info);
  ENCLOSEDBLOCK_R_FL_BRACKET (arg_node) =
    FREETRAV (ENCLOSEDBLOCK_R_FL_BRACKET (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_enclosedblock = MEMfree (arg_node->sons.N_enclosedblock);
  arg_node->attribs.N_enclosedblock =
    MEMfree (arg_node->attribs.N_enclosedblock);
  DBUG_PRINT ("FREE",
	      ("Processing node N_enclosedblock at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEenclosedexpr
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node EnclosedExpr node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEenclosedexpr (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEenclosedexpr");
  DBUG_PRINT ("FREE", ("Processing node N_enclosedexpr at " F_PTR, arg_node));
  ENCLOSEDEXPR_L_BRACKET (arg_node) =
    FREETRAV (ENCLOSEDEXPR_L_BRACKET (arg_node), arg_info);
  ENCLOSEDEXPR_EXPR (arg_node) =
    FREETRAV (ENCLOSEDEXPR_EXPR (arg_node), arg_info);
  ENCLOSEDEXPR_R_BRACKET (arg_node) =
    FREETRAV (ENCLOSEDEXPR_R_BRACKET (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_enclosedexpr = MEMfree (arg_node->sons.N_enclosedexpr);
  arg_node->attribs.N_enclosedexpr =
    MEMfree (arg_node->attribs.N_enclosedexpr);
  DBUG_PRINT ("FREE", ("Processing node N_enclosedexpr at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEequals
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Equals node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEequals (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEequals");
  DBUG_PRINT ("FREE", ("Processing node N_equals at " F_PTR, arg_node));
  result = NULL;
  arg_node->sons.N_equals = MEMfree (arg_node->sons.N_equals);
  arg_node->attribs.N_equals = MEMfree (arg_node->attribs.N_equals);
  DBUG_PRINT ("FREE", ("Processing node N_equals at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEerror
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Error node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEerror (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEerror");
  DBUG_PRINT ("FREE", ("Processing node N_error at " F_PTR, arg_node));
  ERROR_NEXT (arg_node) = FREECOND (ERROR_NEXT (arg_node), arg_info);
  ERROR_MESSAGE (arg_node) =
    FREEattribString (ERROR_MESSAGE (arg_node), arg_node);
  result = ERROR_NEXT (arg_node);
  arg_node->sons.N_error = MEMfree (arg_node->sons.N_error);
  arg_node->attribs.N_error = MEMfree (arg_node->attribs.N_error);
  DBUG_PRINT ("FREE", ("Processing node N_error at " F_PTR, arg_node));
  arg_node = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEexport
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Export node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEexport (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEexport");
  DBUG_PRINT ("FREE", ("Processing node N_export at " F_PTR, arg_node));
  result = NULL;
  arg_node->sons.N_export = MEMfree (arg_node->sons.N_export);
  arg_node->attribs.N_export = MEMfree (arg_node->attribs.N_export);
  DBUG_PRINT ("FREE", ("Processing node N_export at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEexprlist
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node ExprList node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEexprlist (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEexprlist");
  DBUG_PRINT ("FREE", ("Processing node N_exprlist at " F_PTR, arg_node));
  EXPRLIST_NEXT (arg_node) = FREECOND (EXPRLIST_NEXT (arg_node), arg_info);
  EXPRLIST_EXPR (arg_node) = FREETRAV (EXPRLIST_EXPR (arg_node), arg_info);
  result = EXPRLIST_NEXT (arg_node);
  arg_node->sons.N_exprlist = MEMfree (arg_node->sons.N_exprlist);
  arg_node->attribs.N_exprlist = MEMfree (arg_node->attribs.N_exprlist);
  DBUG_PRINT ("FREE", ("Processing node N_exprlist at " F_PTR, arg_node));
  arg_node = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEextern
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Extern node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEextern (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEextern");
  DBUG_PRINT ("FREE", ("Processing node N_extern at " F_PTR, arg_node));
  result = NULL;
  arg_node->sons.N_extern = MEMfree (arg_node->sons.N_extern);
  arg_node->attribs.N_extern = MEMfree (arg_node->attribs.N_extern);
  DBUG_PRINT ("FREE", ("Processing node N_extern at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEfloat
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Float node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEfloat (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEfloat");
  DBUG_PRINT ("FREE", ("Processing node N_float at " F_PTR, arg_node));
  result = NULL;
  arg_node->sons.N_float = MEMfree (arg_node->sons.N_float);
  arg_node->attribs.N_float = MEMfree (arg_node->attribs.N_float);
  DBUG_PRINT ("FREE", ("Processing node N_float at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEfor
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node For node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEfor (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEfor");
  DBUG_PRINT ("FREE", ("Processing node N_for at " F_PTR, arg_node));
  result = NULL;
  arg_node->sons.N_for = MEMfree (arg_node->sons.N_for);
  arg_node->attribs.N_for = MEMfree (arg_node->attribs.N_for);
  DBUG_PRINT ("FREE", ("Processing node N_for at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEfordec
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node ForDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEfordec (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEfordec");
  DBUG_PRINT ("FREE", ("Processing node N_fordec at " F_PTR, arg_node));
  FORDEC_TYPE (arg_node) = FREETRAV (FORDEC_TYPE (arg_node), arg_info);
  FORDEC_FORVARINIT (arg_node) =
    FREETRAV (FORDEC_FORVARINIT (arg_node), arg_info);
  FORDEC_EXPR (arg_node) = FREETRAV (FORDEC_EXPR (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_fordec = MEMfree (arg_node->sons.N_fordec);
  arg_node->attribs.N_fordec = MEMfree (arg_node->attribs.N_fordec);
  DBUG_PRINT ("FREE", ("Processing node N_fordec at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEforstat
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node ForStat node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEforstat (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEforstat");
  DBUG_PRINT ("FREE", ("Processing node N_forstat at " F_PTR, arg_node));
  FORSTAT_FOR (arg_node) = FREETRAV (FORSTAT_FOR (arg_node), arg_info);
  FORSTAT_FORDEC (arg_node) = FREETRAV (FORSTAT_FORDEC (arg_node), arg_info);
  FORSTAT_BLOCK (arg_node) = FREETRAV (FORSTAT_BLOCK (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_forstat = MEMfree (arg_node->sons.N_forstat);
  arg_node->attribs.N_forstat = MEMfree (arg_node->attribs.N_forstat);
  DBUG_PRINT ("FREE", ("Processing node N_forstat at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEforvarinit
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node ForVarInit node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEforvarinit (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEforvarinit");
  DBUG_PRINT ("FREE", ("Processing node N_forvarinit at " F_PTR, arg_node));
  FORVARINIT_VARLET (arg_node) =
    FREETRAV (FORVARINIT_VARLET (arg_node), arg_info);
  FORVARINIT_EQUALS (arg_node) =
    FREETRAV (FORVARINIT_EQUALS (arg_node), arg_info);
  FORVARINIT_EXPR (arg_node) =
    FREETRAV (FORVARINIT_EXPR (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_forvarinit = MEMfree (arg_node->sons.N_forvarinit);
  arg_node->attribs.N_forvarinit = MEMfree (arg_node->attribs.N_forvarinit);
  DBUG_PRINT ("FREE", ("Processing node N_forvarinit at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEfunbody
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node FunBody node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEfunbody (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEfunbody");
  DBUG_PRINT ("FREE", ("Processing node N_funbody at " F_PTR, arg_node));
  result = NULL;
  arg_node->sons.N_funbody = MEMfree (arg_node->sons.N_funbody);
  arg_node->attribs.N_funbody = MEMfree (arg_node->attribs.N_funbody);
  DBUG_PRINT ("FREE", ("Processing node N_funbody at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEfuncall
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node FunCall node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEfuncall (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEfuncall");
  DBUG_PRINT ("FREE", ("Processing node N_funcall at " F_PTR, arg_node));
  FUNCALL_VAR (arg_node) = FREETRAV (FUNCALL_VAR (arg_node), arg_info);
  FUNCALL_EXPRLIST (arg_node) =
    FREETRAV (FUNCALL_EXPRLIST (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_funcall = MEMfree (arg_node->sons.N_funcall);
  arg_node->attribs.N_funcall = MEMfree (arg_node->attribs.N_funcall);
  DBUG_PRINT ("FREE", ("Processing node N_funcall at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEfundec
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node FunDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEfundec (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEfundec");
  DBUG_PRINT ("FREE", ("Processing node N_fundec at " F_PTR, arg_node));
  FUNDEC_EXTERN (arg_node) = FREETRAV (FUNDEC_EXTERN (arg_node), arg_info);
  FUNDEC_FUNHEADER (arg_node) =
    FREETRAV (FUNDEC_FUNHEADER (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_fundec = MEMfree (arg_node->sons.N_fundec);
  arg_node->attribs.N_fundec = MEMfree (arg_node->attribs.N_fundec);
  DBUG_PRINT ("FREE", ("Processing node N_fundec at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEfundef
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node FunDef node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEfundef (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEfundef");
  DBUG_PRINT ("FREE", ("Processing node N_fundef at " F_PTR, arg_node));
  FUNDEF_EXPORT (arg_node) = FREETRAV (FUNDEF_EXPORT (arg_node), arg_info);
  FUNDEF_FUNHEADER (arg_node) =
    FREETRAV (FUNDEF_FUNHEADER (arg_node), arg_info);
  FUNDEF_FUNBODY (arg_node) = FREETRAV (FUNDEF_FUNBODY (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_fundef = MEMfree (arg_node->sons.N_fundef);
  arg_node->attribs.N_fundef = MEMfree (arg_node->attribs.N_fundef);
  DBUG_PRINT ("FREE", ("Processing node N_fundef at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEfunheader
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node FunHeader node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEfunheader (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEfunheader");
  DBUG_PRINT ("FREE", ("Processing node N_funheader at " F_PTR, arg_node));
  FUNHEADER_RETTYPE (arg_node) =
    FREETRAV (FUNHEADER_RETTYPE (arg_node), arg_info);
  FUNHEADER_VAR (arg_node) = FREETRAV (FUNHEADER_VAR (arg_node), arg_info);
  FUNHEADER_PARAMLIST (arg_node) =
    FREETRAV (FUNHEADER_PARAMLIST (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_funheader = MEMfree (arg_node->sons.N_funheader);
  arg_node->attribs.N_funheader = MEMfree (arg_node->attribs.N_funheader);
  DBUG_PRINT ("FREE", ("Processing node N_funheader at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEglobaldec
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node GlobalDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEglobaldec (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEglobaldec");
  DBUG_PRINT ("FREE", ("Processing node N_globaldec at " F_PTR, arg_node));
  GLOBALDEC_EXTERN (arg_node) =
    FREETRAV (GLOBALDEC_EXTERN (arg_node), arg_info);
  GLOBALDEC_TYPE (arg_node) = FREETRAV (GLOBALDEC_TYPE (arg_node), arg_info);
  GLOBALDEC_VAR (arg_node) = FREETRAV (GLOBALDEC_VAR (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_globaldec = MEMfree (arg_node->sons.N_globaldec);
  arg_node->attribs.N_globaldec = MEMfree (arg_node->attribs.N_globaldec);
  DBUG_PRINT ("FREE", ("Processing node N_globaldec at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEglobaldef
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node GlobalDef node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEglobaldef (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEglobaldef");
  DBUG_PRINT ("FREE", ("Processing node N_globaldef at " F_PTR, arg_node));
  GLOBALDEF_EXPORT (arg_node) =
    FREETRAV (GLOBALDEF_EXPORT (arg_node), arg_info);
  GLOBALDEF_TYPE (arg_node) = FREETRAV (GLOBALDEF_TYPE (arg_node), arg_info);
  GLOBALDEF_VAR (arg_node) = FREETRAV (GLOBALDEF_VAR (arg_node), arg_info);
  GLOBALDEF_EXPR (arg_node) = FREETRAV (GLOBALDEF_EXPR (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_globaldef = MEMfree (arg_node->sons.N_globaldef);
  arg_node->attribs.N_globaldef = MEMfree (arg_node->attribs.N_globaldef);
  DBUG_PRINT ("FREE", ("Processing node N_globaldef at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEifkeyword
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node IfKeyword node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEifkeyword (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEifkeyword");
  DBUG_PRINT ("FREE", ("Processing node N_ifkeyword at " F_PTR, arg_node));
  result = NULL;
  arg_node->sons.N_ifkeyword = MEMfree (arg_node->sons.N_ifkeyword);
  arg_node->attribs.N_ifkeyword = MEMfree (arg_node->attribs.N_ifkeyword);
  DBUG_PRINT ("FREE", ("Processing node N_ifkeyword at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEifstat
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node IfStat node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEifstat (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEifstat");
  DBUG_PRINT ("FREE", ("Processing node N_ifstat at " F_PTR, arg_node));
  IFSTAT_IF (arg_node) = FREETRAV (IFSTAT_IF (arg_node), arg_info);
  IFSTAT_L_BRACKET (arg_node) =
    FREETRAV (IFSTAT_L_BRACKET (arg_node), arg_info);
  IFSTAT_EXPR (arg_node) = FREETRAV (IFSTAT_EXPR (arg_node), arg_info);
  IFSTAT_R_BRACKET (arg_node) =
    FREETRAV (IFSTAT_R_BRACKET (arg_node), arg_info);
  IFSTAT_BLOCK (arg_node) = FREETRAV (IFSTAT_BLOCK (arg_node), arg_info);
  IFSTAT_ELSEBLOCK (arg_node) =
    FREETRAV (IFSTAT_ELSEBLOCK (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_ifstat = MEMfree (arg_node->sons.N_ifstat);
  arg_node->attribs.N_ifstat = MEMfree (arg_node->attribs.N_ifstat);
  DBUG_PRINT ("FREE", ("Processing node N_ifstat at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEkey_bool
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Key_Bool node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEkey_bool (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEkey_bool");
  DBUG_PRINT ("FREE", ("Processing node N_key_bool at " F_PTR, arg_node));
  result = NULL;
  arg_node->sons.N_key_bool = MEMfree (arg_node->sons.N_key_bool);
  arg_node->attribs.N_key_bool = MEMfree (arg_node->attribs.N_key_bool);
  DBUG_PRINT ("FREE", ("Processing node N_key_bool at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEkey_float
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Key_Float node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEkey_float (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEkey_float");
  DBUG_PRINT ("FREE", ("Processing node N_key_float at " F_PTR, arg_node));
  result = NULL;
  arg_node->sons.N_key_float = MEMfree (arg_node->sons.N_key_float);
  arg_node->attribs.N_key_float = MEMfree (arg_node->attribs.N_key_float);
  DBUG_PRINT ("FREE", ("Processing node N_key_float at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEkey_int
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Key_Int node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEkey_int (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEkey_int");
  DBUG_PRINT ("FREE", ("Processing node N_key_int at " F_PTR, arg_node));
  result = NULL;
  arg_node->sons.N_key_int = MEMfree (arg_node->sons.N_key_int);
  arg_node->attribs.N_key_int = MEMfree (arg_node->attribs.N_key_int);
  DBUG_PRINT ("FREE", ("Processing node N_key_int at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEkey_void
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Key_Void node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEkey_void (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEkey_void");
  DBUG_PRINT ("FREE", ("Processing node N_key_void at " F_PTR, arg_node));
  result = NULL;
  arg_node->sons.N_key_void = MEMfree (arg_node->sons.N_key_void);
  arg_node->attribs.N_key_void = MEMfree (arg_node->attribs.N_key_void);
  DBUG_PRINT ("FREE", ("Processing node N_key_void at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEl_bracket
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node L_Bracket node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEl_bracket (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEl_bracket");
  DBUG_PRINT ("FREE", ("Processing node N_l_bracket at " F_PTR, arg_node));
  result = NULL;
  arg_node->sons.N_l_bracket = MEMfree (arg_node->sons.N_l_bracket);
  arg_node->attribs.N_l_bracket = MEMfree (arg_node->attribs.N_l_bracket);
  DBUG_PRINT ("FREE", ("Processing node N_l_bracket at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEl_fl_bracket
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node L_FL_Bracket node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEl_fl_bracket (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEl_fl_bracket");
  DBUG_PRINT ("FREE", ("Processing node N_l_fl_bracket at " F_PTR, arg_node));
  result = NULL;
  arg_node->sons.N_l_fl_bracket = MEMfree (arg_node->sons.N_l_fl_bracket);
  arg_node->attribs.N_l_fl_bracket =
    MEMfree (arg_node->attribs.N_l_fl_bracket);
  DBUG_PRINT ("FREE", ("Processing node N_l_fl_bracket at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEmonop
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node MonOp node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEmonop (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEmonop");
  DBUG_PRINT ("FREE", ("Processing node N_monop at " F_PTR, arg_node));
  MONOP_RIGHT (arg_node) = FREETRAV (MONOP_RIGHT (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_monop = MEMfree (arg_node->sons.N_monop);
  arg_node->attribs.N_monop = MEMfree (arg_node->attribs.N_monop);
  DBUG_PRINT ("FREE", ("Processing node N_monop at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEnum
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Num node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEnum (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEnum");
  DBUG_PRINT ("FREE", ("Processing node N_num at " F_PTR, arg_node));
  result = NULL;
  arg_node->sons.N_num = MEMfree (arg_node->sons.N_num);
  arg_node->attribs.N_num = MEMfree (arg_node->attribs.N_num);
  DBUG_PRINT ("FREE", ("Processing node N_num at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEparam
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Param node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEparam (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEparam");
  DBUG_PRINT ("FREE", ("Processing node N_param at " F_PTR, arg_node));
  PARAM_TYPE (arg_node) = FREETRAV (PARAM_TYPE (arg_node), arg_info);
  PARAM_VAR (arg_node) = FREETRAV (PARAM_VAR (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_param = MEMfree (arg_node->sons.N_param);
  arg_node->attribs.N_param = MEMfree (arg_node->attribs.N_param);
  DBUG_PRINT ("FREE", ("Processing node N_param at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEparamlist
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node ParamList node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEparamlist (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEparamlist");
  DBUG_PRINT ("FREE", ("Processing node N_paramlist at " F_PTR, arg_node));
  PARAMLIST_NEXT (arg_node) = FREECOND (PARAMLIST_NEXT (arg_node), arg_info);
  PARAMLIST_PARAM (arg_node) =
    FREETRAV (PARAMLIST_PARAM (arg_node), arg_info);
  result = PARAMLIST_NEXT (arg_node);
  arg_node->sons.N_paramlist = MEMfree (arg_node->sons.N_paramlist);
  arg_node->attribs.N_paramlist = MEMfree (arg_node->attribs.N_paramlist);
  DBUG_PRINT ("FREE", ("Processing node N_paramlist at " F_PTR, arg_node));
  arg_node = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEprogram
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Program node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEprogram (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEprogram");
  DBUG_PRINT ("FREE", ("Processing node N_program at " F_PTR, arg_node));
  PROGRAM_NEXT (arg_node) = FREECOND (PROGRAM_NEXT (arg_node), arg_info);
  PROGRAM_CODEBLOCK (arg_node) =
    FREETRAV (PROGRAM_CODEBLOCK (arg_node), arg_info);
  result = PROGRAM_NEXT (arg_node);
  arg_node->sons.N_program = MEMfree (arg_node->sons.N_program);
  arg_node->attribs.N_program = MEMfree (arg_node->attribs.N_program);
  DBUG_PRINT ("FREE", ("Processing node N_program at " F_PTR, arg_node));
  arg_node = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEr_bracket
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node R_Bracket node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEr_bracket (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEr_bracket");
  DBUG_PRINT ("FREE", ("Processing node N_r_bracket at " F_PTR, arg_node));
  result = NULL;
  arg_node->sons.N_r_bracket = MEMfree (arg_node->sons.N_r_bracket);
  arg_node->attribs.N_r_bracket = MEMfree (arg_node->attribs.N_r_bracket);
  DBUG_PRINT ("FREE", ("Processing node N_r_bracket at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEr_fl_bracket
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node R_FL_Bracket node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEr_fl_bracket (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEr_fl_bracket");
  DBUG_PRINT ("FREE", ("Processing node N_r_fl_bracket at " F_PTR, arg_node));
  result = NULL;
  arg_node->sons.N_r_fl_bracket = MEMfree (arg_node->sons.N_r_fl_bracket);
  arg_node->attribs.N_r_fl_bracket =
    MEMfree (arg_node->attribs.N_r_fl_bracket);
  DBUG_PRINT ("FREE", ("Processing node N_r_fl_bracket at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREErettype
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node RetType node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREErettype (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREErettype");
  DBUG_PRINT ("FREE", ("Processing node N_rettype at " F_PTR, arg_node));
  RETTYPE_SET_RETTYPE (arg_node) =
    FREETRAV (RETTYPE_SET_RETTYPE (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_rettype = MEMfree (arg_node->sons.N_rettype);
  arg_node->attribs.N_rettype = MEMfree (arg_node->attribs.N_rettype);
  DBUG_PRINT ("FREE", ("Processing node N_rettype at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEreturn
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Return node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEreturn (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEreturn");
  DBUG_PRINT ("FREE", ("Processing node N_return at " F_PTR, arg_node));
  RETURN_RETURNKEYWORD (arg_node) =
    FREETRAV (RETURN_RETURNKEYWORD (arg_node), arg_info);
  RETURN_EXPR (arg_node) = FREETRAV (RETURN_EXPR (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_return = MEMfree (arg_node->sons.N_return);
  arg_node->attribs.N_return = MEMfree (arg_node->attribs.N_return);
  DBUG_PRINT ("FREE", ("Processing node N_return at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEreturnkeyword
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node ReturnKeyword node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEreturnkeyword (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEreturnkeyword");
  DBUG_PRINT ("FREE",
	      ("Processing node N_returnkeyword at " F_PTR, arg_node));
  result = NULL;
  arg_node->sons.N_returnkeyword = MEMfree (arg_node->sons.N_returnkeyword);
  arg_node->attribs.N_returnkeyword =
    MEMfree (arg_node->attribs.N_returnkeyword);
  DBUG_PRINT ("FREE",
	      ("Processing node N_returnkeyword at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEstatement
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Statement node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEstatement (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEstatement");
  DBUG_PRINT ("FREE", ("Processing node N_statement at " F_PTR, arg_node));
  STATEMENT_SET_STATEMENT (arg_node) =
    FREETRAV (STATEMENT_SET_STATEMENT (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_statement = MEMfree (arg_node->sons.N_statement);
  arg_node->attribs.N_statement = MEMfree (arg_node->attribs.N_statement);
  DBUG_PRINT ("FREE", ("Processing node N_statement at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEstatementlist
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node StatementList node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEstatementlist (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEstatementlist");
  DBUG_PRINT ("FREE",
	      ("Processing node N_statementlist at " F_PTR, arg_node));
  STATEMENTLIST_NEXT (arg_node) =
    FREECOND (STATEMENTLIST_NEXT (arg_node), arg_info);
  STATEMENTLIST_STATEMENT (arg_node) =
    FREETRAV (STATEMENTLIST_STATEMENT (arg_node), arg_info);
  result = STATEMENTLIST_NEXT (arg_node);
  arg_node->sons.N_statementlist = MEMfree (arg_node->sons.N_statementlist);
  arg_node->attribs.N_statementlist =
    MEMfree (arg_node->attribs.N_statementlist);
  DBUG_PRINT ("FREE",
	      ("Processing node N_statementlist at " F_PTR, arg_node));
  arg_node = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEtype
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Type node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEtype (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEtype");
  DBUG_PRINT ("FREE", ("Processing node N_type at " F_PTR, arg_node));
  TYPE_SET_TYPE (arg_node) = FREETRAV (TYPE_SET_TYPE (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_type = MEMfree (arg_node->sons.N_type);
  arg_node->attribs.N_type = MEMfree (arg_node->attribs.N_type);
  DBUG_PRINT ("FREE", ("Processing node N_type at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEvar
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Var node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEvar (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEvar");
  DBUG_PRINT ("FREE", ("Processing node N_var at " F_PTR, arg_node));
  VAR_NAME (arg_node) = FREEattribString (VAR_NAME (arg_node), arg_node);
  VAR_DECL (arg_node) = FREEattribLink (VAR_DECL (arg_node), arg_node);
  result = NULL;
  arg_node->sons.N_var = MEMfree (arg_node->sons.N_var);
  arg_node->attribs.N_var = MEMfree (arg_node->attribs.N_var);
  DBUG_PRINT ("FREE", ("Processing node N_var at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEvardec
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node VarDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEvardec (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEvardec");
  DBUG_PRINT ("FREE", ("Processing node N_vardec at " F_PTR, arg_node));
  VARDEC_TYPE (arg_node) = FREETRAV (VARDEC_TYPE (arg_node), arg_info);
  VARDEC_VAR (arg_node) = FREETRAV (VARDEC_VAR (arg_node), arg_info);
  VARDEC_EXPR (arg_node) = FREETRAV (VARDEC_EXPR (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_vardec = MEMfree (arg_node->sons.N_vardec);
  arg_node->attribs.N_vardec = MEMfree (arg_node->attribs.N_vardec);
  DBUG_PRINT ("FREE", ("Processing node N_vardec at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEvardeclist
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node VarDecList node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEvardeclist (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEvardeclist");
  DBUG_PRINT ("FREE", ("Processing node N_vardeclist at " F_PTR, arg_node));
  VARDECLIST_NEXT (arg_node) =
    FREECOND (VARDECLIST_NEXT (arg_node), arg_info);
  VARDECLIST_VARDEC (arg_node) =
    FREETRAV (VARDECLIST_VARDEC (arg_node), arg_info);
  result = VARDECLIST_NEXT (arg_node);
  arg_node->sons.N_vardeclist = MEMfree (arg_node->sons.N_vardeclist);
  arg_node->attribs.N_vardeclist = MEMfree (arg_node->attribs.N_vardeclist);
  DBUG_PRINT ("FREE", ("Processing node N_vardeclist at " F_PTR, arg_node));
  arg_node = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEvarlet
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node VarLet node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEvarlet (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEvarlet");
  DBUG_PRINT ("FREE", ("Processing node N_varlet at " F_PTR, arg_node));
  VARLET_NAME (arg_node) =
    FREEattribString (VARLET_NAME (arg_node), arg_node);
  VARLET_DECL (arg_node) = FREEattribLink (VARLET_DECL (arg_node), arg_node);
  result = NULL;
  arg_node->sons.N_varlet = MEMfree (arg_node->sons.N_varlet);
  arg_node->attribs.N_varlet = MEMfree (arg_node->attribs.N_varlet);
  DBUG_PRINT ("FREE", ("Processing node N_varlet at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEwhile
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node While node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEwhile (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEwhile");
  DBUG_PRINT ("FREE", ("Processing node N_while at " F_PTR, arg_node));
  result = NULL;
  arg_node->sons.N_while = MEMfree (arg_node->sons.N_while);
  arg_node->attribs.N_while = MEMfree (arg_node->attribs.N_while);
  DBUG_PRINT ("FREE", ("Processing node N_while at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEwhilestat
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node WhileStat node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEwhilestat (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEwhilestat");
  DBUG_PRINT ("FREE", ("Processing node N_whilestat at " F_PTR, arg_node));
  WHILESTAT_WHILE (arg_node) =
    FREETRAV (WHILESTAT_WHILE (arg_node), arg_info);
  WHILESTAT_EXPR (arg_node) = FREETRAV (WHILESTAT_EXPR (arg_node), arg_info);
  WHILESTAT_BLOCK (arg_node) =
    FREETRAV (WHILESTAT_BLOCK (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_whilestat = MEMfree (arg_node->sons.N_whilestat);
  arg_node->attribs.N_whilestat = MEMfree (arg_node->attribs.N_whilestat);
  DBUG_PRINT ("FREE", ("Processing node N_whilestat at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/**
 * @}
 */
