
/**
 * @file types_nodetype.h
 *
 * This file defines the nodetype node enumeration.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: types_nodetype.h.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#ifndef _SAC_TYPES_NODETYPE_H_
#define _SAC_TYPES_NODETYPE_H_

#define MAX_NODES 55
typedef enum
{ N_undefined = 0, N_const = 1, N_statement = 2, N_program = 3, N_vardec =
    4, N_param = 5, N_type = 6, N_extern = 7, N_export = 8, N_for =
    9, N_equals = 10, N_ifkeyword = 11, N_l_fl_bracket = 12, N_r_fl_bracket =
    13, N_l_bracket = 14, N_r_bracket = 15, N_key_void = 16, N_key_int =
    17, N_key_float = 18, N_key_bool = 19, N_fundec = 20, N_funheader =
    21, N_rettype = 22, N_paramlist = 23, N_fundef = 24, N_funbody =
    25, N_globaldef = 26, N_globaldec = 27, N_vardeclist = 28, N_return =
    29, N_returnkeyword = 30, N_statementlist = 31, N_dowhilestat = 32, N_do =
    33, N_while = 34, N_whilestat = 35, N_forstat = 36, N_fordec =
    37, N_forvarinit = 38, N_funcall = 39, N_exprlist = 40, N_ifstat =
    41, N_elseblock = 42, N_else = 43, N_enclosedblock = 44, N_assign =
    45, N_binop = 46, N_monop = 47, N_cast = 48, N_enclosedexpr =
    49, N_varlet = 50, N_var = 51, N_num = 52, N_float = 53, N_bool =
    54, N_error = 55 } nodetype;

#endif /* _SAC_TYPES_NODETYPE_H_ */
